//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Albums
    {
        public Albums()
        {
            this.Photos = new HashSet<Photos>();
        }
    
        public int AlbumId { get; set; }
        public string AlbumName { get; set; }
        public string AlbumFace { get; set; }
        public string User { get; set; }
    
        public virtual ICollection<Photos> Photos { get; set; }
        public virtual Users Users { get; set; }
    }
}
